spring.application.name=ventas-service
server.port=8081

# MySQL
spring.r2dbc.url=r2dbc:mysql://localhost:3306/ventasdb
spring.r2dbc.username=root
spring.r2dbc.password=root

# Crear tablas automaticamente
spring.sql.init.mode=always

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/ventaslogdb
